Input: image:./akita-inu/0.jpg, identity:akita-inu
Input: image:./akita-inu/1.jpg, identity:akita-inu
Input: image:./akita-inu/2.jpg, identity:akita-inu
Input: image:./akita-inu/3.jpg, identity:akita-inu
Input: image:./akita-inu/4.jpg, identity:akita-inu
Input: image:./akita-inu/5.jpg, identity:akita-inu
Input: image:./akita-inu/6.jpg, identity:akita-inu
Input: image:./akita-inu/7.jpg, identity:akita-inu
Input: image:./alyaskinskij-malamut/0.jpg, identity:alyaskinskij-malamut
Input: image:./alyaskinskij-malamut/1.jpg, identity:alyaskinskij-malamut
Input: image:./alyaskinskij-malamut/2.jpg, identity:alyaskinskij-malamut
Input: image:./alyaskinskij-malamut/3.jpg, identity:alyaskinskij-malamut
Input: image:./alyaskinskij-malamut/4.jpg, identity:alyaskinskij-malamut
Input: image:./alyaskinskij-malamut/5.jpg, identity:alyaskinskij-malamut
Input: image:./alyaskinskij-malamut/6.jpg, identity:alyaskinskij-malamut
Input: image:./alyaskinskij-malamut/7.jpg, identity:alyaskinskij-malamut
Input: image:./amerikanskij-buldog/0.jpg, identity:amerikanskij-buldog
Input: image:./amerikanskij-buldog/1.jpg, identity:amerikanskij-buldog
Input: image:./amerikanskij-buldog/2.jpg, identity:amerikanskij-buldog
Input: image:./amerikanskij-buldog/3.jpg, identity:amerikanskij-buldog
Input: image:./amerikanskij-buldog/4.jpg, identity:amerikanskij-buldog
Input: image:./amerikanskij-buldog/5.jpg, identity:amerikanskij-buldog
Input: image:./amerikanskij-buldog/6.jpg, identity:amerikanskij-buldog
Input: image:./amerikanskij-buldog/7.jpg, identity:amerikanskij-buldog
Input: image:./pitbul/0.jpg, identity:pitbul
Input: image:./pitbul/1.jpg, identity:pitbul
Input: image:./pitbul/2.jpg, identity:pitbul
Input: image:./pitbul/3.jpg, identity:pitbul
Input: image:./pitbul/4.jpg, identity:pitbul
Input: image:./pitbul/5.jpg, identity:pitbul
Input: image:./anglijskij-buldog/0.jpg, identity:anglijskij-buldog
Input: image:./anglijskij-buldog/1.jpg, identity:anglijskij-buldog
Input: image:./anglijskij-buldog/2.jpg, identity:anglijskij-buldog
Input: image:./anglijskij-buldog/3.jpg, identity:anglijskij-buldog
Input: image:./anglijskij-buldog/4.jpg, identity:anglijskij-buldog
Input: image:./anglijskij-buldog/5.jpg, identity:anglijskij-buldog
Input: image:./anglijskij-buldog/6.jpg, identity:anglijskij-buldog
Input: image:./koker-spaniel/0.jpg, identity:koker-spaniel
Input: image:./koker-spaniel/1.jpg, identity:koker-spaniel
Input: image:./koker-spaniel/2.jpg, identity:koker-spaniel
Input: image:./koker-spaniel/3.jpg, identity:koker-spaniel
Input: image:./koker-spaniel/4.jpg, identity:koker-spaniel
Input: image:./koker-spaniel/5.jpg, identity:koker-spaniel
Input: image:./koker-spaniel/6.jpg, identity:koker-spaniel
Input: image:./koker-spaniel/7.jpg, identity:koker-spaniel
Input: image:./koker-spaniel/8.jpg, identity:koker-spaniel
Input: image:./mastif/0.jpg, identity:mastif
Input: image:./mastif/1.jpg, identity:mastif
Input: image:./mastif/2.jpg, identity:mastif
Input: image:./mastif/3.jpg, identity:mastif
Input: image:./mastif/4.jpg, identity:mastif
Input: image:./mastif/5.jpg, identity:mastif
Input: image:./mastif/6.jpg, identity:mastif
Input: image:./mastif/7.jpg, identity:mastif
Input: image:./mastif/8.jpg, identity:mastif
Input: image:./mastif/9.jpg, identity:mastif
Input: image:./mastif/10.jpg, identity:mastif
Input: image:./argentinskij-dog/0.jpg, identity:argentinskij-dog
Input: image:./argentinskij-dog/1.jpg, identity:argentinskij-dog
Input: image:./argentinskij-dog/2.jpg, identity:argentinskij-dog
Input: image:./argentinskij-dog/3.jpg, identity:argentinskij-dog
Input: image:./argentinskij-dog/4.jpg, identity:argentinskij-dog
Input: image:./argentinskij-dog/5.jpg, identity:argentinskij-dog
Input: image:./argentinskij-dog/6.jpg, identity:argentinskij-dog
Input: image:./argentinskij-dog/7.jpg, identity:argentinskij-dog
Input: image:./argentinskij-dog/8.jpg, identity:argentinskij-dog
Input: image:./argentinskij-dog/9.jpg, identity:argentinskij-dog
Input: image:./argentinskij-dog/10.jpg, identity:argentinskij-dog
Input: image:./argentinskij-dog/11.jpg, identity:argentinskij-dog
Input: image:./afganskaya-borzaya/0.jpg, identity:afganskaya-borzaya
Input: image:./afganskaya-borzaya/1.jpg, identity:afganskaya-borzaya
Input: image:./afganskaya-borzaya/2.jpg, identity:afganskaya-borzaya
Input: image:./afganskaya-borzaya/3.jpg, identity:afganskaya-borzaya
Input: image:./afganskaya-borzaya/4.jpg, identity:afganskaya-borzaya
Input: image:./afganskaya-borzaya/5.jpg, identity:afganskaya-borzaya
Input: image:./afganskaya-borzaya/6.jpg, identity:afganskaya-borzaya
Input: image:./afganskaya-borzaya/7.jpg, identity:afganskaya-borzaya
Input: image:./afganskaya-borzaya/8.jpg, identity:afganskaya-borzaya
Input: image:./basendzhi/0.jpg, identity:basendzhi
Input: image:./basendzhi/1.jpg, identity:basendzhi
Input: image:./basendzhi/2.jpg, identity:basendzhi
Input: image:./basendzhi/3.jpg, identity:basendzhi
Input: image:./basendzhi/4.jpg, identity:basendzhi
Input: image:./basendzhi/5.jpg, identity:basendzhi
Input: image:./basendzhi/6.jpg, identity:basendzhi
Input: image:./basendzhi/7.jpg, identity:basendzhi
Input: image:./basendzhi/8.jpg, identity:basendzhi
Input: image:./basset/0.jpg, identity:basset
Input: image:./basset/1.jpg, identity:basset
Input: image:./basset/2.jpg, identity:basset
Input: image:./basset/3.jpg, identity:basset
Input: image:./basset/4.jpg, identity:basset
Input: image:./basset/5.jpg, identity:basset
Input: image:./basset/6.jpg, identity:basset
Input: image:./bernskij-zennenxund/0.jpg, identity:bernskij-zennenxund
Input: image:./bernskij-zennenxund/1.jpg, identity:bernskij-zennenxund
Input: image:./bernskij-zennenxund/2.jpg, identity:bernskij-zennenxund
Input: image:./bernskij-zennenxund/3.jpg, identity:bernskij-zennenxund
Input: image:./bernskij-zennenxund/4.jpg, identity:bernskij-zennenxund
Input: image:./bernskij-zennenxund/5.jpg, identity:bernskij-zennenxund
Input: image:./bernskij-zennenxund/6.jpg, identity:bernskij-zennenxund
Input: image:./bernskij-zennenxund/7.jpg, identity:bernskij-zennenxund
Input: image:./bernskij-zennenxund/8.jpg, identity:bernskij-zennenxund
Input: image:./bernskij-zennenxund/9.jpg, identity:bernskij-zennenxund
Input: image:./bernskij-zennenxund/10.jpg, identity:bernskij-zennenxund
Input: image:./bernskij-zennenxund/11.jpg, identity:bernskij-zennenxund
Input: image:./bigl/0.jpg, identity:bigl
Input: image:./bigl/1.jpg, identity:bigl
Input: image:./bigl/2.jpg, identity:bigl
Input: image:./bigl/3.jpg, identity:bigl
Input: image:./bigl/4.jpg, identity:bigl
Input: image:./bigl/5.jpg, identity:bigl
Input: image:./bigl/6.jpg, identity:bigl
Input: image:./bigl/7.jpg, identity:bigl
Input: image:./bigl/8.jpg, identity:bigl
Input: image:./bigl/9.jpg, identity:bigl
Input: image:./bloodhound/0.jpg, identity:bloodhound
Input: image:./bloodhound/1.jpg, identity:bloodhound
Input: image:./bloodhound/2.jpg, identity:bloodhound
Input: image:./bloodhound/3.jpg, identity:bloodhound
Input: image:./bloodhound/4.jpg, identity:bloodhound
Input: image:./bloodhound/5.jpg, identity:bloodhound
Input: image:./bloodhound/6.jpg, identity:bloodhound
Input: image:./bloodhound/7.jpg, identity:bloodhound
Input: image:./bloodhound/8.jpg, identity:bloodhound
Input: image:./boxer/0.jpg, identity:boxer
Input: image:./boxer/1.jpg, identity:boxer
Input: image:./boxer/2.jpg, identity:boxer
Input: image:./boxer/3.jpg, identity:boxer
Input: image:./boxer/4.jpg, identity:boxer
Input: image:./boxer/5.jpg, identity:boxer
Input: image:./boxer/6.jpg, identity:boxer
Input: image:./boxer/7.jpg, identity:boxer
Input: image:./border-kolli/0.jpg, identity:border-kolli
Input: image:./border-kolli/1.jpg, identity:border-kolli
Input: image:./border-kolli/2.jpg, identity:border-kolli
Input: image:./border-kolli/3.jpg, identity:border-kolli
Input: image:./border-kolli/4.jpg, identity:border-kolli
Input: image:./border-kolli/5.jpg, identity:border-kolli
Input: image:./border-kolli/6.jpg, identity:border-kolli
Input: image:./border-kolli/7.jpg, identity:border-kolli
Input: image:./border-kolli/8.jpg, identity:border-kolli
Input: image:./bordoskij-dog/0.jpg, identity:bordoskij-dog
Input: image:./bordoskij-dog/1.jpg, identity:bordoskij-dog
Input: image:./bordoskij-dog/2.jpg, identity:bordoskij-dog
Input: image:./bordoskij-dog/3.jpg, identity:bordoskij-dog
Input: image:./bordoskij-dog/4.jpg, identity:bordoskij-dog
Input: image:./bordoskij-dog/5.jpg, identity:bordoskij-dog
Input: image:./bordoskij-dog/6.jpg, identity:bordoskij-dog
Input: image:./bordoskij-dog/7.jpg, identity:bordoskij-dog
Input: image:./bordoskij-dog/8.jpg, identity:bordoskij-dog
Input: image:./bordoskij-dog/9.jpg, identity:bordoskij-dog
Input: image:./bordoskij-dog/10.jpg, identity:bordoskij-dog
Input: image:./boseron/0.jpg, identity:boseron
Input: image:./boseron/1.jpg, identity:boseron
Input: image:./boseron/2.jpg, identity:boseron
Input: image:./boseron/3.jpg, identity:boseron
Input: image:./boseron/4.jpg, identity:boseron
Input: image:./boseron/5.jpg, identity:boseron
Input: image:./boseron/6.jpg, identity:boseron
Input: image:./boseron/7.jpg, identity:boseron
Input: image:./boseron/8.jpg, identity:boseron
Input: image:./briar/0.jpg, identity:briar
Input: image:./briar/1.jpg, identity:briar
Input: image:./briar/2.jpg, identity:briar
Input: image:./briar/3.jpg, identity:briar
Input: image:./briar/4.jpg, identity:briar
Input: image:./briar/5.jpg, identity:briar
Input: image:./bryusselskij-griffon/0.jpg, identity:bryusselskij-griffon
Input: image:./bryusselskij-griffon/1.jpg, identity:bryusselskij-griffon
Input: image:./bryusselskij-griffon/2.jpg, identity:bryusselskij-griffon
Input: image:./bryusselskij-griffon/3.jpg, identity:bryusselskij-griffon
Input: image:./bryusselskij-griffon/4.jpg, identity:bryusselskij-griffon
Input: image:./bryusselskij-griffon/5.jpg, identity:bryusselskij-griffon
Input: image:./bryusselskij-griffon/6.jpg, identity:bryusselskij-griffon
Input: image:./bryusselskij-griffon/7.jpg, identity:bryusselskij-griffon
Input: image:./bullmastiff/0.jpg, identity:bullmastiff
Input: image:./bullmastiff/1.jpg, identity:bullmastiff
Input: image:./bullmastiff/2.jpg, identity:bullmastiff
Input: image:./bullmastiff/3.jpg, identity:bullmastiff
Input: image:./bullmastiff/4.jpg, identity:bullmastiff
Input: image:./bullmastiff/5.jpg, identity:bullmastiff
Input: image:./bullmastiff/6.jpg, identity:bullmastiff
Input: image:./bullmastiff/7.jpg, identity:bullmastiff
Input: image:./bullmastiff/8.jpg, identity:bullmastiff
Input: image:./bullmastiff/9.jpg, identity:bullmastiff
Input: image:./bullterrier/0.jpg, identity:bullterrier
Input: image:./bullterrier/1.jpg, identity:bullterrier
Input: image:./bullterrier/2.jpg, identity:bullterrier
Input: image:./bullterrier/3.jpg, identity:bullterrier
Input: image:./bullterrier/4.jpg, identity:bullterrier
Input: image:./bullterrier/5.jpg, identity:bullterrier
Input: image:./bullterrier/6.jpg, identity:bullterrier
Input: image:./bullterrier/7.jpg, identity:bullterrier
Input: image:./bullterrier/8.jpg, identity:bullterrier
Input: image:./bullterrier/9.jpg, identity:bullterrier
Input: image:./byrbyl/0.jpg, identity:byrbyl
Input: image:./byrbyl/1.jpg, identity:byrbyl
Input: image:./byrbyl/2.jpg, identity:byrbyl
Input: image:./byrbyl/3.jpg, identity:byrbyl
Input: image:./byrbyl/4.jpg, identity:byrbyl
Input: image:./byrbyl/5.jpg, identity:byrbyl
Input: image:./byrbyl/6.jpg, identity:byrbyl
Input: image:./byrbyl/7.jpg, identity:byrbyl
Input: image:./byrbyl/8.jpg, identity:byrbyl
Input: image:./korgi/0.jpg, identity:korgi
Input: image:./korgi/1.jpg, identity:korgi
Input: image:./korgi/2.jpg, identity:korgi
Input: image:./korgi/3.jpg, identity:korgi
Input: image:./korgi/4.jpg, identity:korgi
Input: image:./korgi/5.jpg, identity:korgi
Input: image:./korgi/6.jpg, identity:korgi
Input: image:./korgi/7.jpg, identity:korgi
Input: image:./korgi/8.jpg, identity:korgi
Input: image:./korgi/9.jpg, identity:korgi
Input: image:./greyhound/0.jpg, identity:greyhound
Input: image:./greyhound/1.jpg, identity:greyhound
Input: image:./greyhound/2.jpg, identity:greyhound
Input: image:./greyhound/3.jpg, identity:greyhound
Input: image:./greyhound/4.jpg, identity:greyhound
Input: image:./greyhound/5.jpg, identity:greyhound
Input: image:./greyhound/6.jpg, identity:greyhound
Input: image:./greyhound/7.jpg, identity:greyhound
Input: image:./greyhound/8.jpg, identity:greyhound
Input: image:./dalmatin/0.jpg, identity:dalmatin
Input: image:./dalmatin/1.jpg, identity:dalmatin
Input: image:./dalmatin/2.jpg, identity:dalmatin
Input: image:./dalmatin/3.jpg, identity:dalmatin
Input: image:./dalmatin/4.jpg, identity:dalmatin
Input: image:./dalmatin/5.jpg, identity:dalmatin
Input: image:./dalmatin/6.jpg, identity:dalmatin
Input: image:./dalmatin/7.jpg, identity:dalmatin
Input: image:./dalmatin/8.jpg, identity:dalmatin
Input: image:./dzhek-rassel-terer/0.jpg, identity:dzhek-rassel-terer
Input: image:./dzhek-rassel-terer/1.jpg, identity:dzhek-rassel-terer
Input: image:./dzhek-rassel-terer/2.jpg, identity:dzhek-rassel-terer
Input: image:./dzhek-rassel-terer/3.jpg, identity:dzhek-rassel-terer
Input: image:./dzhek-rassel-terer/4.jpg, identity:dzhek-rassel-terer
Input: image:./dzhek-rassel-terer/5.jpg, identity:dzhek-rassel-terer
Input: image:./dzhek-rassel-terer/6.jpg, identity:dzhek-rassel-terer
Input: image:./doberman/0.jpg, identity:doberman
Input: image:./doberman/1.jpg, identity:doberman
Input: image:./doberman/2.jpg, identity:doberman
Input: image:./doberman/3.jpg, identity:doberman
Input: image:./doberman/4.jpg, identity:doberman
Input: image:./doberman/5.jpg, identity:doberman
Input: image:./doberman/6.jpg, identity:doberman
Input: image:./doberman/7.jpg, identity:doberman
Input: image:./zolotistyj-retriver/0.jpg, identity:zolotistyj-retriver
Input: image:./zolotistyj-retriver/1.jpg, identity:zolotistyj-retriver
Input: image:./zolotistyj-retriver/2.jpg, identity:zolotistyj-retriver
Input: image:./zolotistyj-retriver/3.jpg, identity:zolotistyj-retriver
Input: image:./zolotistyj-retriver/4.jpg, identity:zolotistyj-retriver
Input: image:./zolotistyj-retriver/5.jpg, identity:zolotistyj-retriver
Input: image:./zolotistyj-retriver/6.jpg, identity:zolotistyj-retriver
Input: image:./zolotistyj-retriver/7.jpg, identity:zolotistyj-retriver
Input: image:./irlandskij-volkodav/0.jpg, identity:irlandskij-volkodav
Input: image:./irlandskij-volkodav/1.jpg, identity:irlandskij-volkodav
Input: image:./irlandskij-volkodav/2.jpg, identity:irlandskij-volkodav
Input: image:./irlandskij-volkodav/3.jpg, identity:irlandskij-volkodav
Input: image:./irlandskij-volkodav/4.jpg, identity:irlandskij-volkodav
Input: image:./irlandskij-volkodav/5.jpg, identity:irlandskij-volkodav
Input: image:./irlandskij-setter/0.jpg, identity:irlandskij-setter
Input: image:./irlandskij-setter/1.jpg, identity:irlandskij-setter
Input: image:./irlandskij-setter/2.jpg, identity:irlandskij-setter
Input: image:./irlandskij-setter/3.jpg, identity:irlandskij-setter
Input: image:./irlandskij-setter/4.jpg, identity:irlandskij-setter
Input: image:./irlandskij-setter/5.jpg, identity:irlandskij-setter
Input: image:./irlandskij-setter/6.jpg, identity:irlandskij-setter
Input: image:./irlandskij-setter/7.jpg, identity:irlandskij-setter
Input: image:./irlandskij-setter/8.jpg, identity:irlandskij-setter
Input: image:./ispanskij-mastif/0.jpg, identity:ispanskij-mastif
Input: image:./ispanskij-mastif/1.jpg, identity:ispanskij-mastif
Input: image:./ispanskij-mastif/2.jpg, identity:ispanskij-mastif
Input: image:./ispanskij-mastif/3.jpg, identity:ispanskij-mastif
Input: image:./ispanskij-mastif/4.jpg, identity:ispanskij-mastif
Input: image:./ispanskij-mastif/5.jpg, identity:ispanskij-mastif
Input: image:./ispanskij-mastif/6.jpg, identity:ispanskij-mastif
Input: image:./ispanskij-mastif/7.jpg, identity:ispanskij-mastif
Input: image:./ispanskij-mastif/8.jpg, identity:ispanskij-mastif
Input: image:./ispanskij-mastif/9.jpg, identity:ispanskij-mastif
Input: image:./jorkshirskij-terer/0.jpg, identity:jorkshirskij-terer
Input: image:./jorkshirskij-terer/1.jpg, identity:jorkshirskij-terer
Input: image:./jorkshirskij-terer/2.jpg, identity:jorkshirskij-terer
Input: image:./jorkshirskij-terer/3.jpg, identity:jorkshirskij-terer
Input: image:./jorkshirskij-terer/4.jpg, identity:jorkshirskij-terer
Input: image:./jorkshirskij-terer/5.jpg, identity:jorkshirskij-terer
Input: image:./jorkshirskij-terer/6.jpg, identity:jorkshirskij-terer
Input: image:./jorkshirskij-terer/7.jpg, identity:jorkshirskij-terer
Input: image:./kavkazskaya-ovcharka/0.jpg, identity:kavkazskaya-ovcharka
Input: image:./kavkazskaya-ovcharka/1.jpg, identity:kavkazskaya-ovcharka
Input: image:./kavkazskaya-ovcharka/2.jpg, identity:kavkazskaya-ovcharka
Input: image:./kavkazskaya-ovcharka/3.jpg, identity:kavkazskaya-ovcharka
Input: image:./kane-korso/0.jpg, identity:kane-korso
Input: image:./kane-korso/1.jpg, identity:kane-korso
Input: image:./kane-korso/2.jpg, identity:kane-korso
Input: image:./kane-korso/3.jpg, identity:kane-korso
Input: image:./kane-korso/4.jpg, identity:kane-korso
Input: image:./kane-korso/5.jpg, identity:kane-korso
Input: image:./kane-korso/6.jpg, identity:kane-korso
Input: image:./keesxond/0.jpg, identity:keesxond
Input: image:./keesxond/1.jpg, identity:keesxond
Input: image:./keesxond/2.jpg, identity:keesxond
Input: image:./keesxond/3.jpg, identity:keesxond
Input: image:./keesxond/4.jpg, identity:keesxond
Input: image:./keesxond/5.jpg, identity:keesxond
Input: image:./keesxond/6.jpg, identity:keesxond
Input: image:./keesxond/7.jpg, identity:keesxond
Input: image:./keesxond/8.jpg, identity:keesxond
Input: image:./keesxond/9.jpg, identity:keesxond
Input: image:./keesxond/10.jpg, identity:keesxond
Input: image:./kitajskaya-xoxlataya-sobaka/0.jpg, identity:kitajskaya-xoxlataya-sobaka
Input: image:./kitajskaya-xoxlataya-sobaka/1.jpg, identity:kitajskaya-xoxlataya-sobaka
Input: image:./kitajskaya-xoxlataya-sobaka/2.jpg, identity:kitajskaya-xoxlataya-sobaka
Input: image:./kitajskaya-xoxlataya-sobaka/3.jpg, identity:kitajskaya-xoxlataya-sobaka
Input: image:./kitajskaya-xoxlataya-sobaka/4.jpg, identity:kitajskaya-xoxlataya-sobaka
Input: image:./kitajskaya-xoxlataya-sobaka/5.jpg, identity:kitajskaya-xoxlataya-sobaka
Input: image:./kitajskaya-xoxlataya-sobaka/6.jpg, identity:kitajskaya-xoxlataya-sobaka
Input: image:./kitajskaya-xoxlataya-sobaka/7.jpg, identity:kitajskaya-xoxlataya-sobaka
Input: image:./kitajskaya-xoxlataya-sobaka/8.jpg, identity:kitajskaya-xoxlataya-sobaka
Input: image:./kolli/0.jpg, identity:kolli
Input: image:./kolli/1.jpg, identity:kolli
Input: image:./kolli/2.jpg, identity:kolli
Input: image:./kolli/3.jpg, identity:kolli
Input: image:./kolli/4.jpg, identity:kolli
Input: image:./kolli/5.jpg, identity:kolli
Input: image:./kolli/6.jpg, identity:kolli
Input: image:./kolli/7.jpg, identity:kolli
Input: image:./kurcxaar/0.jpg, identity:kurcxaar
Input: image:./kurcxaar/1.jpg, identity:kurcxaar
Input: image:./kurcxaar/2.jpg, identity:kurcxaar
Input: image:./kurcxaar/3.jpg, identity:kurcxaar
Input: image:./kurcxaar/4.jpg, identity:kurcxaar
Input: image:./kurcxaar/5.jpg, identity:kurcxaar
Input: image:./kurcxaar/6.jpg, identity:kurcxaar
Input: image:./kurcxaar/7.jpg, identity:kurcxaar
Input: image:./kurcxaar/8.jpg, identity:kurcxaar
Input: image:./kurcxaar/9.jpg, identity:kurcxaar
Input: image:./labrador/0.jpg, identity:labrador
Input: image:./labrador/1.jpg, identity:labrador
Input: image:./labrador/2.jpg, identity:labrador
Input: image:./labrador/3.jpg, identity:labrador
Input: image:./labrador/4.jpg, identity:labrador
Input: image:./labrador/5.jpg, identity:labrador
Input: image:./labrador/6.jpg, identity:labrador
Input: image:./labrador/7.jpg, identity:labrador
Input: image:./labrador/8.jpg, identity:labrador
Input: image:./labrador/9.jpg, identity:labrador
Input: image:./labrador/10.jpg, identity:labrador
Input: image:./lajka/0.jpg, identity:lajka
Input: image:./lajka/1.jpg, identity:lajka
Input: image:./levretka/0.jpg, identity:levretka
Input: image:./levretka/1.jpg, identity:levretka
Input: image:./levretka/2.jpg, identity:levretka
Input: image:./levretka/3.jpg, identity:levretka
Input: image:./levretka/4.jpg, identity:levretka
Input: image:./levretka/5.jpg, identity:levretka
Input: image:./levretka/6.jpg, identity:levretka
Input: image:./levretka/7.jpg, identity:levretka
Input: image:./leonberger/0.jpg, identity:leonberger
Input: image:./leonberger/1.jpg, identity:leonberger
Input: image:./leonberger/2.jpg, identity:leonberger
Input: image:./leonberger/3.jpg, identity:leonberger
Input: image:./leonberger/4.jpg, identity:leonberger
Input: image:./leonberger/5.jpg, identity:leonberger
Input: image:./leonberger/6.jpg, identity:leonberger
Input: image:./leonberger/7.jpg, identity:leonberger
Input: image:./leonberger/8.jpg, identity:leonberger
Input: image:./leonberger/9.jpg, identity:leonberger
Input: image:./leonberger/10.jpg, identity:leonberger
Input: image:./leonberger/11.jpg, identity:leonberger
Input: image:./leonberger/12.jpg, identity:leonberger
Input: image:./lhasa-apso/0.jpg, identity:lhasa-apso
Input: image:./lhasa-apso/1.jpg, identity:lhasa-apso
Input: image:./lhasa-apso/2.jpg, identity:lhasa-apso
Input: image:./lhasa-apso/3.jpg, identity:lhasa-apso
Input: image:./lhasa-apso/4.jpg, identity:lhasa-apso
Input: image:./lhasa-apso/5.jpg, identity:lhasa-apso
Input: image:./lhasa-apso/6.jpg, identity:lhasa-apso
Input: image:./lhasa-apso/7.jpg, identity:lhasa-apso
Input: image:./lhasa-apso/8.jpg, identity:lhasa-apso
Input: image:./lhasa-apso/9.jpg, identity:lhasa-apso
Input: image:./maltijskaya-bolonka/0.jpg, identity:maltijskaya-bolonka
Input: image:./maltijskaya-bolonka/1.jpg, identity:maltijskaya-bolonka
Input: image:./maltijskaya-bolonka/2.jpg, identity:maltijskaya-bolonka
Input: image:./maltijskaya-bolonka/3.jpg, identity:maltijskaya-bolonka
Input: image:./maltijskaya-bolonka/4.jpg, identity:maltijskaya-bolonka
Input: image:./maltijskaya-bolonka/5.jpg, identity:maltijskaya-bolonka
Input: image:./maltijskaya-bolonka/6.jpg, identity:maltijskaya-bolonka
Input: image:./maltijskaya-bolonka/7.jpg, identity:maltijskaya-bolonka
Input: image:./maltijskaya-bolonka/8.jpg, identity:maltijskaya-bolonka
Input: image:./mittelshnaucer/0.jpg, identity:mittelshnaucer
Input: image:./mittelshnaucer/1.jpg, identity:mittelshnaucer
Input: image:./mittelshnaucer/2.jpg, identity:mittelshnaucer
Input: image:./mittelshnaucer/3.jpg, identity:mittelshnaucer
Input: image:./mittelshnaucer/4.jpg, identity:mittelshnaucer
Input: image:./mops/0.jpg, identity:mops
Input: image:./mops/1.jpg, identity:mops
Input: image:./mops/2.jpg, identity:mops
Input: image:./mops/3.jpg, identity:mops
Input: image:./mops/4.jpg, identity:mops
Input: image:./mops/5.jpg, identity:mops
Input: image:./mops/6.jpg, identity:mops
Input: image:./mops/7.jpg, identity:mops
Input: image:./mops/8.jpg, identity:mops
Input: image:./mops/9.jpg, identity:mops
Input: image:./ovcharka-nemeckaya/0.jpg, identity:ovcharka-nemeckaya
Input: image:./ovcharka-nemeckaya/1.jpg, identity:ovcharka-nemeckaya
Input: image:./ovcharka-nemeckaya/2.jpg, identity:ovcharka-nemeckaya
Input: image:./ovcharka-nemeckaya/3.jpg, identity:ovcharka-nemeckaya
Input: image:./ovcharka-nemeckaya/4.jpg, identity:ovcharka-nemeckaya
Input: image:./ovcharka-nemeckaya/5.jpg, identity:ovcharka-nemeckaya
Input: image:./ovcharka-nemeckaya/6.jpg, identity:ovcharka-nemeckaya
Input: image:./ovcharka-nemeckaya/7.jpg, identity:ovcharka-nemeckaya
Input: image:./ovcharka-nemeckaya/8.jpg, identity:ovcharka-nemeckaya
Input: image:./ovcharka-nemeckaya/9.jpg, identity:ovcharka-nemeckaya
Input: image:./nemeckij-dog/0.jpg, identity:nemeckij-dog
Input: image:./nemeckij-dog/1.jpg, identity:nemeckij-dog
Input: image:./nemeckij-dog/2.jpg, identity:nemeckij-dog
Input: image:./nemeckij-dog/3.jpg, identity:nemeckij-dog
Input: image:./nemeckij-dog/4.jpg, identity:nemeckij-dog
Input: image:./nemeckij-dog/5.jpg, identity:nemeckij-dog
Input: image:./nemeckij-dog/6.jpg, identity:nemeckij-dog
Input: image:./nemeckij-dog/7.jpg, identity:nemeckij-dog
Input: image:./nemeckij-yagdterer/0.jpg, identity:nemeckij-yagdterer
Input: image:./nemeckij-yagdterer/1.jpg, identity:nemeckij-yagdterer
Input: image:./nemeckij-yagdterer/2.jpg, identity:nemeckij-yagdterer
Input: image:./nemeckij-yagdterer/3.jpg, identity:nemeckij-yagdterer
Input: image:./nemeckij-yagdterer/4.jpg, identity:nemeckij-yagdterer
Input: image:./nemeckij-yagdterer/5.jpg, identity:nemeckij-yagdterer
Input: image:./nemeckij-yagdterer/6.jpg, identity:nemeckij-yagdterer
Input: image:./nemeckij-yagdterer/7.jpg, identity:nemeckij-yagdterer
Input: image:./nemeckij-yagdterer/8.jpg, identity:nemeckij-yagdterer
Input: image:./novosotlandskij-retriver/0.jpg, identity:novosotlandskij-retriver
Input: image:./novosotlandskij-retriver/1.jpg, identity:novosotlandskij-retriver
Input: image:./novosotlandskij-retriver/2.jpg, identity:novosotlandskij-retriver
Input: image:./novosotlandskij-retriver/3.jpg, identity:novosotlandskij-retriver
Input: image:./novosotlandskij-retriver/4.jpg, identity:novosotlandskij-retriver
Input: image:./novosotlandskij-retriver/5.jpg, identity:novosotlandskij-retriver
Input: image:./novosotlandskij-retriver/6.jpg, identity:novosotlandskij-retriver
Input: image:./nyufaundlend/0.jpg, identity:nyufaundlend
Input: image:./nyufaundlend/1.jpg, identity:nyufaundlend
Input: image:./nyufaundlend/2.jpg, identity:nyufaundlend
Input: image:./nyufaundlend/3.jpg, identity:nyufaundlend
Input: image:./nyufaundlend/4.jpg, identity:nyufaundlend
Input: image:./nyufaundlend/5.jpg, identity:nyufaundlend
Input: image:./nyufaundlend/6.jpg, identity:nyufaundlend
Input: image:./nyufaundlend/7.jpg, identity:nyufaundlend
Input: image:./nyufaundlend/8.jpg, identity:nyufaundlend
Input: image:./pekines/0.jpg, identity:pekines
Input: image:./pekines/1.jpg, identity:pekines
Input: image:./pekines/2.jpg, identity:pekines
Input: image:./pekines/3.jpg, identity:pekines
Input: image:./pekines/4.jpg, identity:pekines
Input: image:./pekines/5.jpg, identity:pekines
Input: image:./pekines/6.jpg, identity:pekines
Input: image:./pekines/7.jpg, identity:pekines
Input: image:./pekines/8.jpg, identity:pekines
Input: image:./pekines/9.jpg, identity:pekines
Input: image:./peruanskaya-golaya-sobaka/0.jpg, identity:peruanskaya-golaya-sobaka
Input: image:./peruanskaya-golaya-sobaka/1.jpg, identity:peruanskaya-golaya-sobaka
Input: image:./peruanskaya-golaya-sobaka/2.jpg, identity:peruanskaya-golaya-sobaka
Input: image:./peruanskaya-golaya-sobaka/3.jpg, identity:peruanskaya-golaya-sobaka
Input: image:./peruanskaya-golaya-sobaka/4.jpg, identity:peruanskaya-golaya-sobaka
Input: image:./peruanskaya-golaya-sobaka/5.jpg, identity:peruanskaya-golaya-sobaka
Input: image:./peruanskaya-golaya-sobaka/6.jpg, identity:peruanskaya-golaya-sobaka
Input: image:./peruanskaya-golaya-sobaka/7.jpg, identity:peruanskaya-golaya-sobaka
Input: image:./pointer/0.jpg, identity:pointer
Input: image:./pointer/1.jpg, identity:pointer
Input: image:./pointer/2.jpg, identity:pointer
Input: image:./pointer/3.jpg, identity:pointer
Input: image:./pointer/4.jpg, identity:pointer
Input: image:./pointer/5.jpg, identity:pointer
Input: image:./pointer/6.jpg, identity:pointer
Input: image:./pointer/7.jpg, identity:pointer
Input: image:./pointer/8.jpg, identity:pointer
Input: image:./pomeranskij-shpic/0.jpg, identity:pomeranskij-shpic
Input: image:./pomeranskij-shpic/1.jpg, identity:pomeranskij-shpic
Input: image:./pomeranskij-shpic/2.jpg, identity:pomeranskij-shpic
Input: image:./pomeranskij-shpic/3.jpg, identity:pomeranskij-shpic
Input: image:./pomeranskij-shpic/4.jpg, identity:pomeranskij-shpic
Input: image:./pomeranskij-shpic/5.jpg, identity:pomeranskij-shpic
Input: image:./pomeranskij-shpic/6.jpg, identity:pomeranskij-shpic
Input: image:./pomeranskij-shpic/7.jpg, identity:pomeranskij-shpic
Input: image:./pomeranskij-shpic/8.jpg, identity:pomeranskij-shpic
Input: image:./pudel/0.jpg, identity:pudel
Input: image:./pudel/1.jpg, identity:pudel
Input: image:./pudel/2.jpg, identity:pudel
Input: image:./pudel/3.jpg, identity:pudel
Input: image:./pudel/4.jpg, identity:pudel
Input: image:./pudel/5.jpg, identity:pudel
Input: image:./pudel/6.jpg, identity:pudel
Input: image:./pudel/7.jpg, identity:pudel
Input: image:./pudel/8.jpg, identity:pudel
Input: image:./pudel/9.jpg, identity:pudel
Input: image:./pudel/10.jpg, identity:pudel
Input: image:./rizenshnaucer/0.jpg, identity:rizenshnaucer
Input: image:./rizenshnaucer/1.jpg, identity:rizenshnaucer
Input: image:./rizenshnaucer/2.jpg, identity:rizenshnaucer
Input: image:./rizenshnaucer/3.jpg, identity:rizenshnaucer
Input: image:./rizenshnaucer/4.jpg, identity:rizenshnaucer
Input: image:./rizenshnaucer/5.jpg, identity:rizenshnaucer
Input: image:./rizenshnaucer/6.jpg, identity:rizenshnaucer
Input: image:./rizenshnaucer/7.jpg, identity:rizenshnaucer
Input: image:./rizenshnaucer/8.jpg, identity:rizenshnaucer
Input: image:./rotvejler/0.jpg, identity:rotvejler
Input: image:./rotvejler/1.jpg, identity:rotvejler
Input: image:./rotvejler/2.jpg, identity:rotvejler
Input: image:./rotvejler/3.jpg, identity:rotvejler
Input: image:./rotvejler/4.jpg, identity:rotvejler
Input: image:./rotvejler/5.jpg, identity:rotvejler
Input: image:./rotvejler/6.jpg, identity:rotvejler
Input: image:./rotvejler/7.jpg, identity:rotvejler
Input: image:./rotvejler/8.jpg, identity:rotvejler
Input: image:./rotvejler/9.jpg, identity:rotvejler
Input: image:./russkaya-psovaya-borzaya/0.jpg, identity:russkaya-psovaya-borzaya
Input: image:./russkaya-psovaya-borzaya/1.jpg, identity:russkaya-psovaya-borzaya
Input: image:./russkaya-psovaya-borzaya/2.jpg, identity:russkaya-psovaya-borzaya
Input: image:./russkaya-psovaya-borzaya/3.jpg, identity:russkaya-psovaya-borzaya
Input: image:./russkaya-psovaya-borzaya/4.jpg, identity:russkaya-psovaya-borzaya
Input: image:./russkaya-psovaya-borzaya/5.jpg, identity:russkaya-psovaya-borzaya
Input: image:./russkaya-psovaya-borzaya/6.jpg, identity:russkaya-psovaya-borzaya
Input: image:./russkaya-psovaya-borzaya/7.jpg, identity:russkaya-psovaya-borzaya
Input: image:./russkaya-psovaya-borzaya/8.jpg, identity:russkaya-psovaya-borzaya
Input: image:./samoedskaya-sobaka/0.jpg, identity:samoedskaya-sobaka
Input: image:./samoedskaya-sobaka/1.jpg, identity:samoedskaya-sobaka
Input: image:./samoedskaya-sobaka/2.jpg, identity:samoedskaya-sobaka
Input: image:./samoedskaya-sobaka/3.jpg, identity:samoedskaya-sobaka
Input: image:./samoedskaya-sobaka/4.jpg, identity:samoedskaya-sobaka
Input: image:./samoedskaya-sobaka/5.jpg, identity:samoedskaya-sobaka
Input: image:./samoedskaya-sobaka/6.jpg, identity:samoedskaya-sobaka
Input: image:./samoedskaya-sobaka/7.jpg, identity:samoedskaya-sobaka
Input: image:./samoedskaya-sobaka/8.jpg, identity:samoedskaya-sobaka
Input: image:./samoedskaya-sobaka/9.jpg, identity:samoedskaya-sobaka
Input: image:./samoedskaya-sobaka/10.jpg, identity:samoedskaya-sobaka
Input: image:./senbernar/0.jpg, identity:senbernar
Input: image:./senbernar/1.jpg, identity:senbernar
Input: image:./senbernar/2.jpg, identity:senbernar
Input: image:./senbernar/3.jpg, identity:senbernar
Input: image:./senbernar/4.jpg, identity:senbernar
Input: image:./senbernar/5.jpg, identity:senbernar
Input: image:./senbernar/6.jpg, identity:senbernar
Input: image:./senbernar/7.jpg, identity:senbernar
Input: image:./senbernar/8.jpg, identity:senbernar
Input: image:./senbernar/9.jpg, identity:senbernar
Input: image:./senbernar/10.jpg, identity:senbernar
Input: image:./sibirskij-xaski/0.jpg, identity:sibirskij-xaski
Input: image:./sibirskij-xaski/1.jpg, identity:sibirskij-xaski
Input: image:./sibirskij-xaski/2.jpg, identity:sibirskij-xaski
Input: image:./sibirskij-xaski/3.jpg, identity:sibirskij-xaski
Input: image:./sibirskij-xaski/4.jpg, identity:sibirskij-xaski
Input: image:./sibirskij-xaski/5.jpg, identity:sibirskij-xaski
Input: image:./sibirskij-xaski/6.jpg, identity:sibirskij-xaski
Input: image:./sibirskij-xaski/7.jpg, identity:sibirskij-xaski
Input: image:./sibirskij-xaski/8.jpg, identity:sibirskij-xaski
Input: image:./sibirskij-xaski/9.jpg, identity:sibirskij-xaski
Input: image:./taksa/0.jpg, identity:taksa
Input: image:./taksa/1.jpg, identity:taksa
Input: image:./taksa/2.jpg, identity:taksa
Input: image:./taksa/3.jpg, identity:taksa
Input: image:./taksa/4.jpg, identity:taksa
Input: image:./taksa/5.jpg, identity:taksa
Input: image:./taksa/6.jpg, identity:taksa
Input: image:./taksa/7.jpg, identity:taksa
Input: image:./taksa/8.jpg, identity:taksa
Input: image:./taksa/9.jpg, identity:taksa
Input: image:./taksa/10.jpg, identity:taksa
Input: image:./tibetskij-mastif/0.jpg, identity:tibetskij-mastif
Input: image:./tibetskij-mastif/1.jpg, identity:tibetskij-mastif
Input: image:./tibetskij-mastif/2.jpg, identity:tibetskij-mastif
Input: image:./tibetskij-mastif/3.jpg, identity:tibetskij-mastif
Input: image:./tibetskij-mastif/4.jpg, identity:tibetskij-mastif
Input: image:./tibetskij-mastif/5.jpg, identity:tibetskij-mastif
Input: image:./tibetskij-mastif/6.jpg, identity:tibetskij-mastif
Input: image:./tibetskij-mastif/7.jpg, identity:tibetskij-mastif
Input: image:./tibetskij-mastif/8.jpg, identity:tibetskij-mastif
Input: image:./tibetskij-mastif/9.jpg, identity:tibetskij-mastif
Input: image:./tibetskij-mastif/10.jpg, identity:tibetskij-mastif
Input: image:./foxterer/0.jpg, identity:foxterer
Input: image:./foxterer/1.jpg, identity:foxterer
Input: image:./foxterer/2.jpg, identity:foxterer
Input: image:./foxterer/3.jpg, identity:foxterer
Input: image:./foxterer/4.jpg, identity:foxterer
Input: image:./foxterer/5.jpg, identity:foxterer
Input: image:./foxterer/6.jpg, identity:foxterer
Input: image:./foxterer/7.jpg, identity:foxterer
Input: image:./foxterer/8.jpg, identity:foxterer
Input: image:./foxterer/9.jpg, identity:foxterer
Input: image:./foxterer/10.jpg, identity:foxterer
Input: image:./francuzskij-buldog/0.jpg, identity:francuzskij-buldog
Input: image:./francuzskij-buldog/1.jpg, identity:francuzskij-buldog
Input: image:./francuzskij-buldog/2.jpg, identity:francuzskij-buldog
Input: image:./francuzskij-buldog/3.jpg, identity:francuzskij-buldog
Input: image:./francuzskij-buldog/4.jpg, identity:francuzskij-buldog
Input: image:./francuzskij-buldog/5.jpg, identity:francuzskij-buldog
Input: image:./francuzskij-buldog/6.jpg, identity:francuzskij-buldog
Input: image:./francuzskij-buldog/7.jpg, identity:francuzskij-buldog
Input: image:./francuzskij-buldog/8.jpg, identity:francuzskij-buldog
Input: image:./cvergshnaucer/0.jpg, identity:cvergshnaucer
Input: image:./cvergshnaucer/1.jpg, identity:cvergshnaucer
Input: image:./cvergshnaucer/2.jpg, identity:cvergshnaucer
Input: image:./cvergshnaucer/3.jpg, identity:cvergshnaucer
Input: image:./cvergshnaucer/4.jpg, identity:cvergshnaucer
Input: image:./cvergshnaucer/5.jpg, identity:cvergshnaucer
Input: image:./cvergshnaucer/6.jpg, identity:cvergshnaucer
Input: image:./cvergshnaucer/7.jpg, identity:cvergshnaucer
Input: image:./cvergshnaucer/8.jpg, identity:cvergshnaucer
Input: image:./chau-chau/0.jpg, identity:chau-chau
Input: image:./chau-chau/1.jpg, identity:chau-chau
Input: image:./chau-chau/2.jpg, identity:chau-chau
Input: image:./chau-chau/3.jpg, identity:chau-chau
Input: image:./chau-chau/4.jpg, identity:chau-chau
Input: image:./chau-chau/5.jpg, identity:chau-chau
Input: image:./chau-chau/6.jpg, identity:chau-chau
Input: image:./chau-chau/7.jpg, identity:chau-chau
Input: image:./chau-chau/8.jpg, identity:chau-chau
Input: image:./chau-chau/9.jpg, identity:chau-chau
Input: image:./chernyj-terer/0.jpg, identity:chernyj-terer
Input: image:./chernyj-terer/1.jpg, identity:chernyj-terer
Input: image:./chernyj-terer/2.jpg, identity:chernyj-terer
Input: image:./chernyj-terer/3.jpg, identity:chernyj-terer
Input: image:./chernyj-terer/4.jpg, identity:chernyj-terer
Input: image:./chernyj-terer/5.jpg, identity:chernyj-terer
Input: image:./chernyj-terer/6.jpg, identity:chernyj-terer
Input: image:./chernyj-terer/7.jpg, identity:chernyj-terer
Input: image:./chernyj-terer/8.jpg, identity:chernyj-terer
Input: image:./chexoslovackaya-volchya-sobaka/0.jpg, identity:chexoslovackaya-volchya-sobaka
Input: image:./chixuaxua/0.jpg, identity:chixuaxua
Input: image:./chixuaxua/1.jpg, identity:chixuaxua
Input: image:./chixuaxua/2.jpg, identity:chixuaxua
Input: image:./chixuaxua/3.jpg, identity:chixuaxua
Input: image:./chixuaxua/4.jpg, identity:chixuaxua
Input: image:./chixuaxua/5.jpg, identity:chixuaxua
Input: image:./chixuaxua/6.jpg, identity:chixuaxua
Input: image:./chixuaxua/7.jpg, identity:chixuaxua
Input: image:./chixuaxua/8.jpg, identity:chixuaxua
Input: image:./chixuaxua/9.jpg, identity:chixuaxua
Input: image:./sharpej/0.jpg, identity:sharpej
Input: image:./sharpej/1.jpg, identity:sharpej
Input: image:./sharpej/2.jpg, identity:sharpej
Input: image:./sharpej/3.jpg, identity:sharpej
Input: image:./sharpej/4.jpg, identity:sharpej
Input: image:./sharpej/5.jpg, identity:sharpej
Input: image:./sharpej/6.jpg, identity:sharpej
Input: image:./sharpej/7.jpg, identity:sharpej
Input: image:./sharpej/8.jpg, identity:sharpej
Input: image:./sharpej/9.jpg, identity:sharpej
Input: image:./sharpej/10.jpg, identity:sharpej
Input: image:./shelti/0.jpg, identity:shelti
Input: image:./shelti/1.jpg, identity:shelti
Input: image:./shelti/2.jpg, identity:shelti
Input: image:./shelti/3.jpg, identity:shelti
Input: image:./shelti/4.jpg, identity:shelti
Input: image:./shelti/5.jpg, identity:shelti
Input: image:./shelti/6.jpg, identity:shelti
Input: image:./shelti/7.jpg, identity:shelti
Input: image:./shi-tcu/0.jpg, identity:shi-tcu
Input: image:./shi-tcu/1.jpg, identity:shi-tcu
Input: image:./shi-tcu/2.jpg, identity:shi-tcu
Input: image:./shi-tcu/3.jpg, identity:shi-tcu
Input: image:./shi-tcu/4.jpg, identity:shi-tcu
Input: image:./shi-tcu/5.jpg, identity:shi-tcu
Input: image:./shi-tcu/6.jpg, identity:shi-tcu
Input: image:./shi-tcu/7.jpg, identity:shi-tcu
Input: image:./shi-tcu/8.jpg, identity:shi-tcu
Input: image:./shi-tcu/9.jpg, identity:shi-tcu
Input: image:./shi-tcu/10.jpg, identity:shi-tcu
Input: image:./skotch-terer/0.jpg, identity:skotch-terer
Input: image:./skotch-terer/1.jpg, identity:skotch-terer
Input: image:./skotch-terer/2.jpg, identity:skotch-terer
Input: image:./skotch-terer/3.jpg, identity:skotch-terer
Input: image:./skotch-terer/4.jpg, identity:skotch-terer
Input: image:./skotch-terer/5.jpg, identity:skotch-terer
Input: image:./skotch-terer/6.jpg, identity:skotch-terer
Input: image:./erdelterer/0.jpg, identity:erdelterer
Input: image:./erdelterer/1.jpg, identity:erdelterer
Input: image:./erdelterer/2.jpg, identity:erdelterer
Input: image:./erdelterer/3.jpg, identity:erdelterer
Input: image:./erdelterer/4.jpg, identity:erdelterer
Input: image:./erdelterer/5.jpg, identity:erdelterer
Input: image:./erdelterer/6.jpg, identity:erdelterer
Input: image:./erdelterer/7.jpg, identity:erdelterer
Input: image:./erdelterer/8.jpg, identity:erdelterer
Input: image:./erdelterer/9.jpg, identity:erdelterer
Input: image:./yaponskij-xin/0.jpg, identity:yaponskij-xin
Input: image:./yaponskij-xin/1.jpg, identity:yaponskij-xin
Input: image:./yaponskij-xin/2.jpg, identity:yaponskij-xin
Input: image:./yaponskij-xin/3.jpg, identity:yaponskij-xin
Input: image:./yaponskij-xin/4.jpg, identity:yaponskij-xin
Input: image:./yaponskij-xin/5.jpg, identity:yaponskij-xin
Input: image:./yaponskij-xin/6.jpg, identity:yaponskij-xin
Input: image:./yaponskij-xin/7.jpg, identity:yaponskij-xin
Input: image:./yaponskij-xin/8.jpg, identity:yaponskij-xin
