CreateTraining: width:25,height:25,type:RGB
Input: identity:akita-inu
Input: identity:alyaskinskij-malamut
Input: identity:amerikanskij-buldog
Input: identity:pitbul
Input: identity:anglijskij-buldog
Input: identity:koker-spaniel
Input: identity:mastif
Input: identity:argentinskij-dog
Input: identity:afganskaya-borzaya
Input: identity:basendzhi
Input: identity:basset
Input: identity:bernskij-zennenxund
Input: identity:bigl
Input: identity:bloodhound
Input: identity:boxer
Input: identity:border-kolli
Input: identity:bordoskij-dog
Input: identity:boseron
Input: identity:briar
Input: identity:bryusselskij-griffon
Input: identity:bullmastiff
Input: identity:bullterrier
Input: identity:byrbyl
Input: identity:korgi
Input: identity:greyhound
Input: identity:dalmatin
Input: identity:dzhek-rassel-terer
Input: identity:doberman
Input: identity:zolotistyj-retriver
Input: identity:irlandskij-volkodav
Input: identity:irlandskij-setter
Input: identity:ispanskij-mastif
Input: identity:jorkshirskij-terer
Input: identity:kavkazskaya-ovcharka
Input: identity:kane-korso
Input: identity:keesxond
Input: identity:kitajskaya-xoxlataya-sobaka
Input: identity:kolli
Input: identity:kurcxaar
Input: identity:labrador
Input: identity:lajka
Input: identity:levretka
Input: identity:leonberger
Input: identity:lhasa-apso
Input: identity:maltijskaya-bolonka
Input: identity:mittelshnaucer
Input: identity:mops
Input: identity:ovcharka-nemeckaya
Input: identity:nemeckij-dog
Input: identity:nemeckij-yagdterer
Input: identity:novosotlandskij-retriver
Input: identity:nyufaundlend
Input: identity:pekines
Input: identity:peruanskaya-golaya-sobaka
Input: identity:pointer
Input: identity:pomeranskij-shpic
Input: identity:pudel
Input: identity:rizenshnaucer
Input: identity:rotvejler
Input: identity:russkaya-psovaya-borzaya
Input: identity:samoedskaya-sobaka
Input: identity:senbernar
Input: identity:sibirskij-xaski
Input: identity:taksa
Input: identity:tibetskij-mastif
Input: identity:foxterer
Input: identity:francuzskij-buldog
Input: identity:cvergshnaucer
Input: identity:chau-chau
Input: identity:chernyj-terer
Input: identity:chexoslovackaya-volchya-sobaka
Input: identity:chixuaxua
Input: identity:sharpej
Input: identity:shelti
Input: identity:shi-tcu
Input: identity:skotch-terer
Input: identity:erdelterer
Input: identity:yaponskij-xin
Input: identity:english-springer-spaniel
LoadNet: file: ./theBestNet2_4pErr_25x25_800-500-250-150-90_3d.eg
LoadTrainData: file: ./dogs_25x25x3_79_14388.egb
Train: Mode:guic, Minutes:10, StrategyError:0.5, StrategyCycles:150
Whatis: image:./alyaskinskij-malamut/7.jpg
Whatis: image:./alyaskinskij-malamut/6.jpg
Whatis: image:./alyaskinskij-malamut/5.jpg
Whatis: image:./alyaskinskij-malamut/4.jpg
Whatis: image:./alyaskinskij-malamut/3.jpg
Whatis: image:./alyaskinskij-malamut/2.jpg
Whatis: image:./alyaskinskij-malamut/1.jpg
Whatis: image:./alyaskinskij-malamut/0.jpg
Whatis: image:./akita-inu/7.jpg
Whatis: image:./akita-inu/6.jpg
Whatis: image:./akita-inu/5.jpg
Whatis: image:./akita-inu/4.jpg
Whatis: image:./akita-inu/3.jpg
Whatis: image:./akita-inu/2.jpg
Whatis: image:./akita-inu/1.jpg
Whatis: image:./akita-inu/0.jpg
Whatis: image:./nyufaundlend/1201.jpg
Whatis: image:./nyufaundlend/501.jpg
Whatis: image:./nyufaundlend/301.jpg
Whatis: image:./nyufaundlend/201.jpg
Whatis: image:./nyufaundlend/1.jpg
SaveNet: file:./dogsAfterTrain.eg