package ru.electronikas.dogsexpert.neural;

import ru.electronikas.dogsexpert.Assets;

/**
 * AutoGenerated by BreedEnumGenerator.
 */
public enum Breed {
    akita_inu,
    alyaskinskij_malamut,
    amerikanskij_buldog,
    pitbul,
    anglijskij_buldog,
    koker_spaniel,
    mastif,
    argentinskij_dog,
    afganskaya_borzaya,
    basendzhi,
    basset,
    bernskij_zennenxund,
    bigl,
    bloodhound,
    boxer,
    border_kolli,
    bordoskij_dog,
    boseron,
    briar,
    bryusselskij_griffon,
    bullmastiff,
    bullterrier,
    byrbyl,
    korgi,
    greyhound,
    dalmatin,
    dzhek_rassel_terer,
    doberman,
    zolotistyj_retriver,
    irlandskij_volkodav,
    irlandskij_setter,
    ispanskij_mastif,
    jorkshirskij_terer,
    kavkazskaya_ovcharka,
    kane_korso,
    keesxond,
    kitajskaya_xoxlataya_sobaka,
    kolli,
    kurcxaar,
    labrador,
    lajka,
    levretka,
    leonberger,
    lhasa_apso,
    maltijskaya_bolonka,
    mittelshnaucer,
    mops,
    ovcharka_nemeckaya,
    nemeckij_dog,
    nemeckij_yagdterer,
    novosotlandskij_retriver,
    nyufaundlend,
    pekines,
    peruanskaya_golaya_sobaka,
    pointer,
    pomeranskij_shpic,
    pudel,
    rizenshnaucer,
    rotvejler,
    russkaya_psovaya_borzaya,
    samoedskaya_sobaka,
    senbernar,
    sibirskij_xaski,
    taksa,
    tibetskij_mastif,
    foxterer,
    francuzskij_buldog,
    cvergshnaucer,
    chau_chau,
    chernyj_terer,
    chexoslovackaya_volchya_sobaka,
    chixuaxua,
    sharpej,
    shelti,
    shi_tcu,
    skotch_terer,
    erdelterer,
    yaponskij_xin,
    english_springer_spaniel,;

    private int percent = 0;

    public void setResult(double result) {
        percent = (int) Math.round((result + 1) * 50);
    }

    public int getPercent() {
        return percent;
    }

    public String getDescription() {
        return Assets.bdl().get(this.name());
    }

    public String getImagePath() {
        return "data/breeds/" + this.name() + "/0.jpg";
    }

    public static int size() {
        return values().length;
    }
}